apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: dev-portal
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          kube:
            port: 8080
            ref:
              name: dev-portal
              namespace: dev-portal