apiVersion: discovery.mesh.gloo.solo.io/v1
kind: Destination
metadata:
  name: aws-external-access
  namespace: gloo-mesh
spec:
  externalService:
    hosts:
      - "*.amazonaws.com"
    name: amazon-aws
    ports:
      - name: https
        number: 443
        protocol: HTTPS